spring.application.name=WanderMap

spring.datasource.url=jdbc:postgresql://localhost:5432/wandermap
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
